name = "gbr_ui_router"
version = "1.0.2-alpha001"
target = "javascript"

description = "📡 Gleam UI SPA router library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-br", repo = "gbr_ui_router" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gbr_js = { path = "../gbr_js" }
gleam_stdlib = "~> 0.68"

[dev-dependencies]
gleeunit = "~> 1.9.0"

[javascript]
typescript_declarations = true
